<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>CtfileDownloader</AssemblyName>
    <RootNamespace>CtfileDownloader</RootNamespace>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <DebugType>none</DebugType>
    <SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
    <NeutralLanguage>zh-Hans</NeutralLanguage>
  </PropertyGroup>

</Project>
